# Neural Networks and Deep Learning

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os

In [ ]:
os.chdir('/content/drive/MyDrive/Colab Notebooks/data-vision/day12')

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')

In [ ]:
df
# 갱신 0, 갱신 안했으면 1(exited)
# Exited 컬럼을 0, 1로 분류의 문제 (SVM, decision tree, 등으로도 할 수 있으나)

# 딥러닝으로 해보기

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [ ]:
X = df.iloc[:, 3:-1 ]

In [ ]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [ ]:
y = df['Exited']

In [ ]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
X.shape

(10000, 10)

In [ ]:
y.shape

(10000,)

In [ ]:
X.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [ ]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [ ]:
# 위의 컬럼 Geograpyh와 Gender는 문제가 있다
# Geography가 ['France', 'Spain', 'Germany'] 등이 반복되므로 One Hot Encoding을 해줘야 하고
# Gender는 Female, Male 이므로 0, 1로 바꿔주는 Label Encoding을 해준다

# 여기서 용어는 중요!!!

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelEncoder_gender = LabelEncoder()

In [ ]:
X['Gender'] = labelEncoder_gender.fit_transform(X ['Gender'])

In [ ]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France       0  ...          1               1        101348.88
1          608     Spain       0  ...          0               1        112542.58
2          502    France       0  ...          1               0        113931.57
3          699    France       0  ...          0               0         93826.63
4          850     Spain       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer( [ ( 'encoder', OneHotEncoder(), [1]) ], remainder='passthrough' )

In [ ]:
# 유니크 확인
X['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
# dypte=np.float는 실수로 만드는 것인데 생략해도 된다
X = np.array( ct.fit_transform(X), dtype=np.float)

In [ ]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [ ]:
X.shape

(10000, 12)

In [ ]:
# 기술 면접시 나올 수 있음! 중요 Dummy varialbe trap :
# One Hot Encoding을 한 후 맨 왼쪽 컬럼을 지워도 분류하는데 구별하는데는 문제가 없어서 
# 즉 맨 왼쪽 하나의 컬럼은 지워도 된다. 
# Dummy variable trap 이라고 함

# 0 0 1 => 0 1
# 0 1 0 => 1 0
# 1 0 0 => 0 0

In [ ]:
# X의 첫번째 컬럼은 없애고, 1번째 컬럼부터 끝까지 가져오기
# numpy에서 데이터 액세스 [ row, col ]
# row는 다 가져오고 column은 인덱스 1부터 가져오기
# Dummy Variable 하기
X = X[ : , 1: ]

feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
# X의 값이 편차가 크기 때문에 피쳐스 스케일링을 해줘야 한다
X_scaled = sc.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0)

Modeling

In [ ]:
여태껏 머신러닝은 알고리즘으로 (문제를 해결하기 위한 순서와 방법) 해결한 것이었음
딥러닝은 알고리즘으로 돌아가는 것이 아니고, 인공 신경망을 이용해서 수학식(방정식), 액티베이션 함수으로 
돌아가는 것
y = ax1 + bx2 + cx3 + e ( x는 컬럼의 값들이 들어가짐) Linear Regression에서 한 방정식
이 처럼 이 공식이 뉴런에 왼쪽의 공식에 들어가짐

여기에서는 11개 컬럼이 되어서 (One Hot Encoding으로, Label Encoding)
input layer의 뉴런이 11개가 되는셈 (컬럼 수가 결정)

ax1 + bx2 + cx3 + dx4 .... kx11 + q
컴퓨터는 여기에서는 a, b, c... x 값을 찾는 것 
인공신경망 그림에서는 선 들을 의미한다 == w 라고 하고 == weight == 가중치 라고 함


텐서플로우 불러오기

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
Gradient Descent
기울기는 미분
기울기를 구했으면 마이너스를 해준다. 그러면 내리가는 것 +면 올라가는 것
한발 내려가고 오차계산하고  (여기서 한발 내려간다는 의미는 )
입력에서 (output)까지 계산한 것을 다시 w를 다 바꿔주면서 (update)를 해준 다음에
입력까지 다시 와서 다시 오차 계산을 해주는 것을 (한발 내려간것)

Stochastic Gradient Descent (sgd) 라고 함

Sequential()생성

In [ ]:
classifier = Sequential()

In [ ]:
X_scaled.shape
# Input layer의 입력 뉴런이 11개 된다 (컬럼 수와 동일)

(10000, 11)

In [ ]:
# layer는 Dense라고 하며 Dense()를 사용

.add (Dense ()) 레이어 추가

In [ ]:
# units = layer 들을 의미 
# input layer 옆에 있는 layer
classifier.add( Dense( input_dim = 11, units = 6, activation='relu') )

In [ ]:
# Vanishing Gradient 현상
# Activation Functions를 Sigmoid, Tanh를 hidden layer에서 설정해놓으면
# Sigmoid, Tanh가 0이 되버리면 오차계산이 다 안 끝났는데 계산이 끝나버리면서 
# 오차가 생겨버리는 현상 
# 그래서 Sigmoid, Tanh 함수는 히든레이어에서는 사용하지 않는다

# activation=tf.nn.relu 는 액티베이션 함수 지정인데 위의 
# activation='relu' 와 같은 의미
classifier.add( Dense( units= 8, activation=tf.nn.relu) )


In [ ]:
# 마지막 outlayer 설정 // 마지막에는 sigmoid 함수를 사용할 수 있다
classifier.add( Dense( units=1, activation=tf.nn.sigmoid) ) #같은 표현 == activation='sigmoid'

In [ ]:
# complie => loss 함수 (오차 함수)를 무엇으로 할지, 옵티마이저는 무엇으로 할지 결정

complie 설정

In [ ]:
# loss= 오차 계산하는 방식 'binary_crossentropy' 
# optimizer='adam' 잘 모르겠으면 adam 함수, 
# 참고로: sgd 도 있었음 Stochastic Gradient Descent

In [ ]:
classifier.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'] )

학습

In [ ]:
# epochs --> 한정된 데이터를 가지고 다시 입력을 다시 해서 w가중치를 계속바꿀 수 있으므로
# 다시 반복해서 학습하게 하는 것 (오차가 줄어듬)
# batch_size=10 ---> 행렬로 한꺼번에 대입해서 계산하게 함

# ** 중요 두 번 실행하면 학습을 했던 데이터를 가지고 다시 학습 하기 때문에 
# 파라미터를 바꿔서 할 때는 처음 객체 생성부터 다시 실행 시켜줘야한다
classifier.fit(X_train, y_train, epochs=20, batch_size=10)

Epoch 1/20
800/800 [==============================] - 1s 928us/step - loss: 0.5705 - accuracy: 0.7650
Epoch 2/20
800/800 [==============================] - 1s 944us/step - loss: 0.4386 - accuracy: 0.8174
Epoch 3/20
800/800 [==============================] - 1s 986us/step - loss: 0.4154 - accuracy: 0.8171
Epoch 4/20
800/800 [==============================] - 1s 943us/step - loss: 0.4045 - accuracy: 0.8249
Epoch 5/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3770 - accuracy: 0.8403
Epoch 6/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3667 - accuracy: 0.8448
Epoch 7/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3582 - accuracy: 0.8511
Epoch 8/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3577 - accuracy: 0.8490
Epoch 9/20
800/800 [==============================] - 1s 931us/step - loss: 0.3483 - accuracy: 0.8519
Epoch 10/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3496 - accura

In [ ]:
#loss는 학습하면 생긴 오차 (binary_crossent ropy 함수를 이용) 낮을 수록 좋다
accuracy 정확도는 (compusion matrix로 계산) 높을 수록 좋음

In [ ]:
# Part 2 - Now let's make the ANN!

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Part 3 - Making the predictions and evaluating the model

In [ ]:
# 방법1 인공지능이 예측한 결과가 0~1 사이의 실수(float)로 나오게 하는 방법
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([[0.2774694 ],
       [0.36949635],
       [0.21106881],
       ...,
       [0.14270371],
       [0.17253593],
       [0.2247886 ]], dtype=float32)

In [ ]:
y_pred.min()

0.0051096976

In [ ]:
y_pred.max()

0.99998724

In [ ]:
0과 1사이로 min(), max()로 나오게 되는데
마지막 output layer를 시그모이드 함수를 사용했기 때문에
0과 1만 나오게 되며
분류의 문제로 다룰 수 있다

In [ ]:
# 0.5 보다 크면 true처리하게 변수 저장
y_pred > 0.5


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
# 방법2 예법 결과를 0과 1사이가 아니라, 0 또는 1로 딱 떨어지게 나오게 하는 방법

In [ ]:
y_pred = classifier.predict_classes(X_test)
# predict_classes(X_test)를 사용하는데 이거는 deprecated 됨

# np.argmax(model.predict(x), axis=-1) 라고 쓰라고 함

# 바이너리 0, 1 2개로 분류하는 것이면 model.predict(x) > 0.5 이렇게 하라고 함
# multi-class classification이면 3개이상의 분류이면 위의 코드는 맞지 않으므로 정확한 결과가 안나옴
# 그래서 y_pred > 0.5를 사용하면 됨

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [ ]:
값이 0과 1로 바뀜

In [ ]:
y_pred.min()

0

In [ ]:
y_pred.max()

1

In [ ]:
# 바뀐 방법 
# 위의 예제와는 맞지 않음
# y_pred_new = np.argmax(classifier.predict(X_test), axis=-1)

In [ ]:
y_pred_new

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_pred_new.max()
# max()값이 1이 안나옴

0

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

array([[1525,   70],
       [ 207,  198]])

In [ ]:
# 정확도 계산

In [ ]:
(1525 + 198) / cm.sum()

0.8615

In [ ]:
# 정확도 계산하는 라이브러리, 위에서 불러온 모듈 accracy_score 함수를 사용

In [ ]:
accuracy_score(y_test, y_pred)

0.8615

![2%E1%84%83%E1%85%A1%E1%84%8B%E1%85%AE%E1%86%AB%E1%84%85%E1%85%A9%E1%84%83%E1%85%B3.png](attachment:2%E1%84%83%E1%85%A1%E1%84%8B%E1%85%AE%E1%86%AB%E1%84%85%E1%85%A9%E1%84%83%E1%85%B3.png)

In [ ]:
# 로스와 정확도만 따로 볼때

In [ ]:
# evaluate() 메소드 
# loss 값과 accuracy값을 리턴해 준다
test_loss, test_acc = classifier.evaluate(X_test, y_test)

63/63 [==============================] - 0s 775us/step - loss: 0.3418 - accuracy: 0.8615


In [ ]:
print('loss = ', test_loss)

loss =  0.34175440669059753


In [ ]:
print('accuracy = ', test_acc)

accuracy =  0.8615000247955322


## 다음 신규 데이터를 통해 분류해 보자

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40
- Tenure: 3
- Balance: 60000
- Number of Products: 2
- Has Credit Card: Yes
- Is Active Member: Yes
- Estimated Salary: 50000

In [ ]:
X1 = np.array([ 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000])

In [ ]:
# 원래 One Hot Encoding을 해야하는데  
# 'France', 'Spain', 'Germany'  1 0 0 으로 변환된다고 가정
# Dummy variable trap 으로 앞에 컬럼을 지운다고 가정


In [ ]:
# feature scaling

In [ ]:
sc.transform(X1)

ValueError: ignored

In [ ]:
# 위의 안내 참고
# Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
X1 = X1.reshape(1, -1)

In [ ]:
X1_scaled = sc.transform(X1)

In [ ]:
y_pred_X1 = classifier.predict(X1_scaled)

In [ ]:
y_pred_X1

array([[0.02913624]], dtype=float32)

In [ ]:
y_pred_X1 > 0.5

array([[False]])

In [ ]:
# 예측결과는 0 / 가입안한다


    ## 또 예측해보기
    Geography: Spain
    Credit Score: 1100
    Gender: Fmale
    Age: 30
    Tenure: 2
    Balance: 85000
    Number of Products: 4
    Has Credit Card: Yes
    Is Active Member: Yes
    Estimated Salary: 150000


In [ ]:
df.head(1)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1

[1 rows x 14 columns]

In [ ]:
# Spain 0 1 0
X2 = np.array( [ 0, 1, 0, 1100, 0, 30, 2, 85000, 4, 1, 1, 150000 ] )

In [ ]:
# Dummpy trap 제거한걸로 가정
X2 = np.array( [ 1, 0, 1100, 0, 30, 2, 85000, 4, 1, 1, 150000 ] )

In [ ]:
# Featurs Scaling
# 먼저 X2를 reshape() 를 해야함


In [ ]:
X2.shape

(11,)

In [ ]:
# 데이터는 행으로 한줄에 들어가 있고, 11개 컬럼으로 이므로 
X2 = X2.reshape(1, -1)

In [ ]:
# transform(X2) 학습한 것 토대로 transform()해줌
X2_scaled = sc.transform(X2)

In [ ]:
# 예측

In [ ]:
y_pred_X2 = classifier.predict(X2)

In [ ]:
y_pred_X2

array([[1.]], dtype=float32)

In [ ]:
# 가입한다

### 용어 정리

epoch

- 한 번의 epoch는 신경망에서 전체 데이터 셋에 대해 forward pass/backward pass 과정을 거친 것을 말함. 즉, 전체 데이터 셋에 대해 한 번 학습을 완료한 상태


batch_size

메모리의 한계와 속도 저하 때문에 대부분의 경우에는 한 번의 epoch에서 모든 데이터를 한꺼번에 집어넣을 수는 없습니다. 그래서 데이터를 나누어서 주게 되는데 이때 몇 번 나누어서 주는가를 iteration, 각 iteration마다 주는 데이터 사이즈를 batch size라고 합니다.

출처: https://www.slideshare.net/w0ong/ss-82372826

![20190123_182720.png](attachment:20190123_182720.png)

In [ ]:
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


In [ ]:
#모델링이면 
#1. Sequential
#2. Dense 
#3. complie 
# 순서로 만듬


In [ ]:
# 위의 순서를 사용자 함수로 만들기
def build_classifier(optimizer) :
  classifier = Sequential()
  classifier.add( Dense( input_dim = 11, units = 6, activation='relu') )
  classifier.add( Dense( units= 8, activation=tf.nn.relu) )
  classifier.add( Dense( units=1, activation=tf.nn.sigmoid) )
  classifier.compile(loss='binary_crossentropy', optimizer = optimizer , metrics=['accuracy'] )
  return classifier


KerasClassifier 생성

In [ ]:
# build_fn= 파라미터
# 사용자 함수를 지정할 수 있음
classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
param = {
    'batch_size' : [10, 20, 25],
    'epochs': [200, 500, 700],
    'optimizer': ['adam', 'rmsprop'] 
}

In [ ]:
# scoring='accuray' 대개 정확도를 선택
# cv= 원래 있던 트렌인셋을 10개로 쪼개서 더 정교하게 학습을 시키는 것
# 부분 돌아가면서 학습을 함,
# cross validation
grid_search = GridSearchCV(estimator= classifier, param_grid=param, scoring='accuracy', cv=10)

In [ ]:
grid_search.fit(X_train, y_train)

Epoch 1/200
720/720 [==============================] - 1s 910us/step - loss: 0.5348 - accuracy: 0.7880
Epoch 2/200
720/720 [==============================] - 1s 971us/step - loss: 0.4494 - accuracy: 0.8026
Epoch 3/200
720/720 [==============================] - 1s 950us/step - loss: 0.4372 - accuracy: 0.8027
Epoch 4/200
720/720 [==============================] - 1s 966us/step - loss: 0.4290 - accuracy: 0.8095
Epoch 5/200
720/720 [==============================] - 1s 942us/step - loss: 0.4176 - accuracy: 0.8196
Epoch 6/200
720/720 [==============================] - 1s 897us/step - loss: 0.4115 - accuracy: 0.8318
Epoch 7/200
720/720 [==============================] - 1s 981us/step - loss: 0.4126 - accuracy: 0.8261
Epoch 8/200
720/720 [==============================] - 1s 980us/step - loss: 0.4079 - accuracy: 0.8288
Epoch 9/200
720/720 [==============================] - 1s 999us/step - loss: 0.3984 - accuracy: 0.8334
Epoch 10/200
720/720 [==============================] - 1s 1ms/step - los

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Streaming output truncated to the last 5000 lines.
Epoch 342/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3382 - accuracy: 0.8716
Epoch 343/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3632 - accuracy: 0.8479
Epoch 344/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3288 - accuracy: 0.8665
Epoch 345/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3226 - accuracy: 0.8760
Epoch 346/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8684
Epoch 347/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3464 - accuracy: 0.8605
Epoch 348/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3591 - accuracy: 0.8552
Epoch 349/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3483 - accuracy: 0.8590
Epoch 350/700
720/720 [==============================] - 1s 2ms/step - loss: 0.3425 - accuracy: 0.8660
Epoch 351/700
720/720 

![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202019-10-11%2013.43.59.png](attachment:%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202019-10-11%2013.43.59.png)