In [3]:
import numpy as np

In [5]:
x = np.array( [1, 2, 3, 4, 5])

In [6]:
x

array([1, 2, 3, 4, 5])

In [7]:
type(x)

numpy.ndarray

In [8]:
x.shape

(5,)

In [16]:
x.dtype

dtype('int32')

In [7]:
matrix = np.array([[1, 2], [3, 4]])

In [8]:
matrix

array([[1, 2],
       [3, 4]])

In [9]:
matrix.shape

(2, 2)

In [10]:
matrix.size

4

In [11]:
np.save('my_array', matrix)

In [12]:
y = np.load('my_array.npy')

In [13]:
y

array([[1, 2],
       [3, 4]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
a = np.zeros( (3, 4) )

In [18]:
a.dtype

dtype('float64')

In [19]:
a.shape

(3, 4)

In [20]:
#특정값으로 채우기
np.full ( (2, 3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [21]:
np.full ( (3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [23]:
# arange() 메소드 사용
np.arange(10+1)  # +1은 포함안함 (마지막 숫자 포함 안함)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#arange(start, end)
np.arange(2, 20+1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [ ]:
#arange()의 args
#np.arange(start, stop, step) 
#arange()는 int 타입으로 만들어 준다

In [25]:
np.arange(1, 29+1, 2)  #step값을 2씩 건너뜀, 홀수

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [26]:
np.arange(2, 20+1, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#arange()의 아규먼트랑은 차이가 좀 있다, 마지막 아규먼트는 step값
#linspace()의 마지막 아규먼트는 개수 임
#그리고 linspace()는 실수형을 만든다
#np.linspace (start, stop, how many)

In [27]:
np.linspace(0, 25, 10)  

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [28]:
np.linspace(0, 25, 10, endpoint=False)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [ ]:
#먼저 1차원 벡터로 만들고 그 후에 reshape() 사용하기

In [29]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
x = np.arange(20)

In [32]:
x.size
x.dtype

dtype('int32')

In [ ]:
# reshape()
# args: 2차원 형태로 넣어준다. row, col

In [33]:
X = x.reshape(4, 5)

In [35]:
X.shape

(4, 5)

In [1]:
#한번에 메소드들 연결해서 사용

In [5]:
X = np.arange(20).reshape(4, 5)

In [6]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
X = np.arange(1, 29+1, 2).reshape(3, 5)

In [13]:
X

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [14]:
#실수로 만들기

In [18]:
X = np.linspace(2, 20, 10, endpoint=False).reshape(2, 5)


In [19]:
X

array([[ 2. ,  3.8,  5.6,  7.4,  9.2],
       [11. , 12.8, 14.6, 16.4, 18.2]])

In [ ]:
#np의 random. 사용하기
# 파이썬의 기본모듈 random이 아닌, numpy의 random
# 기본모듈의 random()과 randint() 사용법 같음

In [20]:
np.random.random()

0.18072531077556842

In [22]:
np.random.randint(10)

6

In [23]:
np.random.randint(1, 6, 10)  #범위 (start, stop, 개수)

array([3, 2, 5, 5, 3, 5, 2, 1, 3, 4])

In [ ]:
#정규분포 랜덤값을 채우기
# 정규분포 (가우시안 분포)
# np.random.normal(mean, standard deviation, size=shape(행, 렬))

In [24]:
np.random.normal(3, 0.5, 1)

array([3.36278532])

In [25]:
#170대의 평균치 10, 행렬

In [26]:
np.random.normal(170, 10, (1000, 1000))

array([[151.88949797, 162.6233337 , 173.84161333, ..., 181.37610751,
        176.60618991, 171.37960005],
       [174.26883937, 190.22611677, 160.6005043 , ..., 154.93275284,
        162.99805005, 178.53609376],
       [183.77086541, 154.77188779, 176.20587692, ..., 159.44640334,
        158.6326542 , 193.94299355],
       ...,
       [169.48846833, 173.73534932, 178.7889972 , ..., 172.19998692,
        164.32587172, 172.78384197],
       [181.51111721, 192.67283921, 183.34390842, ..., 176.97974189,
        174.91913954, 149.44843882],
       [175.57983881, 171.35875326, 159.57277513, ..., 171.00703012,
        160.57338617, 158.31440866]])

In [27]:
X = np.random.normal(170, 10, (2000, 2000))

In [28]:
X.shape

(2000, 2000)

In [29]:
X.dtype

dtype('float64')

In [30]:
X.max()

220.32780186854603

In [31]:
X.min()

121.11637768016548

In [33]:
X.mean()  #평균 구하기 mean()

169.9942932605014

In [34]:
X.sum()

679977173.0420055

In [38]:
np.arange(2, 32+1, 2).reshape(4, 4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])