import np,pd,plt

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [60]:
df = pd.read_csv('Data.csv')

In [3]:
df
# 여기에서 Country 컬럼이 categorical 데이터임을 확인

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

1. NaN데이터 처리 isna()

In [61]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

1-1 dropna() 컬럼으로 하면 안됨axis=1

In [59]:
df.dropna(axis = 0)
# 행으로만 지우기

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

1-2 fillna() 채우기 mean()활용

In [6]:
#평균값으로 채우기
df.mean()

Age          38.777778
Salary    63777.777778
dtype: float64

In [62]:
df.fillna(df.mean(), inplace=True)

2. X,y 데이터 분리

In [8]:
#df에서 Country컬럼과 Age, Salary은 학습시킬 데이터가 된다
# x가 됨

#df 에서 Purchased 컬럼을 학습 (예측)결과로 사용할 것임
# y가 된다. 레이블링 변수라고도 함

In [63]:
X = df.iloc[ :, 0:2+1]  #뒤의 슬라이싱은 포함안하므로 +1


In [10]:
X.head(2)

Country   Age   Salary
0  France  44.0  72000.0
1   Spain  27.0  48000.0

In [64]:
y = df.iloc[ :, -1]

In [12]:
y.head(2)

0     No
1    Yes
Name: Purchased, dtype: object

3. covert from string to number 컴퓨터가 이해할 수 있게 문자열에서 숫자로 바꾸기
Label Encoding

3-1 Label Encoding

In [13]:
# 먼저 Label Encoding 방식으로 숫자로 바꿔줌
# 숫자가 아닌 데이터 중 (문자열) 카테고리컬 문자를 숫자로 바꿔줌

LabelEncoder, OneHotEncoder 불러오기

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [65]:
# 인스턴스
label_X = LabelEncoder()

fit_transform( X[컬럼]) Label Encoding

In [66]:
# 위에서 data학습용으로 만든 X에서 Country컬럼만 바꿔주기
label_X.fit_transform( X['Country'] )

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [17]:
#위에 결과에 보면 숫자로 바뀐것을 알 수 있음
# 알파벳 순으로 바뀜
# 원래 컬럼과 비교
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [67]:
# X의 컬럼 업데이트
X['Country'] = label_X.fit_transform( X['Country'])

In [19]:
X.head(3)

Country   Age   Salary
0        0  44.0  72000.0
1        2  27.0  48000.0
2        1  30.0  54000.0

In [20]:
# 하지만 이런 숫자로 바뀐 것도 학습에는 적합하지 않다고 함
# 그래서 One Hot Encoding을 해줘야 함
# 숫자를 해당컬럼을 unique한 갯수만큼 컬럼을 늘려서
# 해당하는 컬럼에만 1을 주고, 나머지는 0이 입력됨

# 이게 머신러닝 학습이 잘 되서 One Hot Encoding을 한다고 함
# 예:
# 애플    치킨    브로컬리
# 1   0   0
# 0   1   0
# 0   0   1


ColumnTransformer 불러오기 (OneHotEncoder를 하기위함)

In [21]:
# One Hot Encoder를 하기 위한 ColumnTransformer 불러오기
from sklearn.compose import ColumnTransformer

In [68]:
# [('one_hot_encoder', OneHotEncoder(), [0])] 
# 여기에서 [0]번째의 의미는 DataFrame에서 바꿀 컬럼 'Country'컬럼이 0번째 이므로 그 컬럼만 바꾸라는 의미
# 다른 데이터에서는 상황에 맞게 바꿔 줘야함
# remainder='passthrough'----> 다른 컬럼은 바꾸지 않는다

# ct 생성, 0번째가 OneHotEncoder() 클래스?를 사용하는 놈으로 생성, 미리 셋팅 한다고 생각
ct = ColumnTransformer( [ ('one_hot_encoder', OneHotEncoder(), [0]) ], remainder='passthrough' )

fit_transform(X)사용하기

In [69]:
# X 학습할 데이터를 fit_transform()메소드를 사용해서 사용함
ct.fit_transform(X)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [24]:
# 위에서 보면 fit_transform() 메소드를 사용하면
# OneHotEncoder()를 해서 컬럼이 3개가 늘어 남
# 원래는 컨츄리, 에이지, 샐러리 인데 
# 컨츄리 부분이 0 0 0 으로 늘어난것을 알 수 있음
# 0번째 row의 0번째 컬럼이 1로 셋팅된것을 알 수 있음

# France에 해당하면 1 0 0 
# Spane에 해당되면 0 1 0
# Germany에 해당하면 0 0 1 이런식으로... 3개 컬럼이 만들어 짐
# 이게 바로 One Hoe Encoding

In [70]:
# 생성된 결과를 X로 넣어주기
X = ct.fit_transform(X)

결과 값 y도 Label Encoding

In [71]:
#학습정답인 y는 라벨 인코딩만 시켜준다
# 인스턴스 생성
label_y  = LabelEncoder()

In [72]:
# y는 purchased 가 문자열이 숫자로 바뀌는 것
label_y.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [73]:
# 라벨 인코딩한 것 y에 저장
y = label_y.fit_transform(y)

4. dataSet을 Train과 Test로 나누기 

In [29]:
#Train은 훈련용
#Test는 예측용


train_test_split 불러오기

In [30]:
from sklearn.model_selection import train_test_split

In [74]:
#train_test_split(  X(학습데이터), y(정답데이터), test_size=, random_state=)

# train 80%, test 20% 정도 할당
# test_size 파라미터는 1이 최대치 
# 그래서 test_size는 0.2
# random_state = seed값을 주는 것 
# 다른 사람도 결과가 같게 나옴

train_test_split(X, y, test_size=0.2, random_state = 123)


[array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
         7.90000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
         5.80000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
         8.30000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
         6.10000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
         4.80000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
         5.20000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
         6.70000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
         5.40000000e+04]]),
 array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
         6.37777778e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
         7.20000000e+04]]),
 array

In [75]:
# train_test_split()을 하면 알아서 훈련용과 예측test용이 나눠진다
# 4개로 나눠짐
# 4개의 변수로 저장
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
# 여기서 X_train 학습의 정답은 y_train
# x_test 예측용 데이터의 정답은 y_test가 된다

5. Feature Scaling 하기 (2가지방법)
둘 중의 하나로 선택 (standardization과 normalization 중 하나만 선택, 비슷하다고 함)

StandardScaler사용 (Standardization) 

In [33]:
#Standardisation / Normalisation 중 
#1. Standardisation 방법 (StandardScaler)


In [34]:
from sklearn.preprocessing import StandardScaler

In [76]:
#인스턴스
sc_X = StandardScaler()

In [77]:
#훈련용 데이터를 Standardisation 하기
# Standardisation의 공식대로 대입해서 변환해줌
sc_X.fit_transform(X_train)

array([[ 1.29099445, -0.57735027, -0.77459667,  1.35276221,  1.36880027],
       [ 1.29099445, -0.57735027, -0.77459667, -0.40095722, -0.40011085],
       [-0.77459667,  1.73205081, -0.77459667,  1.6225652 ,  1.70573573],
       [-0.77459667, -0.57735027,  1.29099445,  0.00374726, -0.14740926],
       [-0.77459667, -0.57735027,  1.29099445, -1.48016918, -1.24244948],
       [-0.77459667, -0.57735027,  1.29099445,  0.10867065, -0.90551403],
       [ 1.29099445, -0.57735027, -0.77459667, -0.13115423,  0.35799392],
       [-0.77459667,  1.73205081, -0.77459667, -1.07546469, -0.7370463 ]])

In [78]:
#저장
X_train = sc_X.fit_transform(X_train)

In [79]:
#test용도 저장
X_test = sc_X.fit_transform(X_test)

In [39]:
#2. Normalisation 방법 (MinMaxScaler)

MinMaxScaler() Normalization

In [40]:
from sklearn.preprocessing import MinMaxScaler

In [41]:
mm_X = MinMaxScaler()

In [42]:
# 위에서 X_train을 standardisation방법으로 feature scaling을 했기 때문에 
# X_train데이터를 다시 만들어 줘야한다


In [43]:
# 바로 이코드를 다시 해야함
train_test_split(X, y, test_size=0.2, random_state=123)

[array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
         7.90000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
         5.80000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
         8.30000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
         6.10000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
         4.80000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
         5.20000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
         6.70000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
         5.40000000e+04]]),
 array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
         6.37777778e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
         7.20000000e+04]]),
 7    

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [45]:
# normalisation하기 , X_train과 X_test 
# normalisation은 1,0으로 만듬

mm_X.fit_transform(X_train)

array([[1.        , 0.        , 0.        , 0.91304348, 0.88571429],
       [1.        , 0.        , 0.        , 0.34782609, 0.28571429],
       [0.        , 1.        , 0.        , 1.        , 1.        ],
       [0.        , 0.        , 1.        , 0.47826087, 0.37142857],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.51207729, 0.11428571],
       [1.        , 0.        , 0.        , 0.43478261, 0.54285714],
       [0.        , 1.        , 0.        , 0.13043478, 0.17142857]])

In [46]:
mm_X.fit_transform(X_test)

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1.]])

In [47]:
# 위의 MinMaxScaler를 이용해서 normalization을 하려면
# 각각 X_train, X_test에 저장해줘야함

In [48]:
X_train = mm_X.fit_transform(X_train)

In [49]:
X_test = mm_X.fit_transform(X_test)

학습시키기 regressor

In [50]:
from sklearn.linear_model import LinearRegression

In [80]:
X_train.shape

(8, 5)

In [81]:
y_train.shape

(8,)

In [82]:
# 인스턴스 생성
regressor = LinearRegression()

인공지능객체.fit

In [83]:
regressor.fit(X_train, y_train)

LinearRegression()

인공지능객체.predict(X_test)

In [85]:
y_pred = regressor.predict(X_test)

In [86]:
y_pred

array([0.08618669, 0.91381331])

In [87]:
y_test - y_pred

array([ 0.91381331, -0.91381331])

In [89]:
X_test.shape

(2, 5)

In [90]:
y_test.shape

(2,)

In [94]:
# y_test를 2차원으로 만들기
y_test1 = y_test.reshape(-1, 1)

In [97]:
y_test1.shape

(2, 1)